# Generated by Django 3.0 on 2023-02-04 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=255, null=True)),
                ('s_state', models.CharField(blank=True, max_length=255, null=True)),
                ('s_city', models.CharField(blank=True, max_length=255, null=True)),
                ('s_address', models.CharField(blank=True, max_length=255, null=True)),
                ('s_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TvBrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_brand', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_service', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(blank=True, max_length=255, null=True)),
                ('service_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopBrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('tv_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_name', models.CharField(blank=True, max_length=255, null=True)),
                ('n_city', models.CharField(blank=True, max_length=255, null=True)),
                ('n_state', models.CharField(blank=True, max_length=255, null=True)),
                ('n_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('n_address', models.CharField(blank=True, max_length=255, null=True)),
                ('n_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
