# Generated by Django 3.0 on 2023-02-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_shop_s_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='n_city',
            field=models.CharField(blank=True, choices=[('Nagpur', 'Nagpur')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='n_state',
            field=models.CharField(blank=True, choices=[('Maharashtra', 'Maharashtra')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='s_city',
            field=models.CharField(blank=True, choices=[('Maharashtra', 'Maharashtra')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='s_state',
            field=models.CharField(blank=True, choices=[('Nagpur', 'Nagpur')], max_length=255, null=True),
        ),
    ]
