# Generated by Django 2.2.27 on 2023-02-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20230205_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='s_image',
            field=models.ImageField(blank=True, null=True, upload_to='Shop_images/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='s_city',
            field=models.CharField(blank=True, choices=[('Nagpur', 'Nagpur')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='s_state',
            field=models.CharField(blank=True, choices=[('Maharashtra', 'Maharashtra')], max_length=255, null=True),
        ),
    ]
