# Generated by Django 2.2.27 on 2023-02-14 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20230214_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_city', models.CharField(blank=True, choices=[('Nagpur', 'Nagpur')], max_length=255, null=True)),
                ('r_state', models.CharField(blank=True, choices=[('Maharashtra', 'Maharashtra')], max_length=255, null=True)),
                ('r_address', models.TextField(blank=True, null=True)),
                ('r_TvBrand', models.CharField(blank=True, max_length=255, null=True)),
                ('r_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('r_status', models.CharField(blank=True, choices=[('Maharashtra', 'Maharashtra')], default='Pending', max_length=255, null=True)),
                ('shop_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Shop')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.NormalUser')),
            ],
        ),
    ]
