# Generated by Django 2.2.5 on 2022-05-03 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 22, 47, 45, 515116), verbose_name='date published'),
        ),
    ]
