# Generated by Django 2.2.5 on 2022-05-04 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220504_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 7, 38, 13, 323724), verbose_name='date published'),
        ),
    ]
