# Generated by Django 2.2.5 on 2023-04-26 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230427_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='role',
            field=models.CharField(default='wedfjenj', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 1, 44, 42, 297066), verbose_name='date published'),
        ),
    ]
