# Generated by Django 2.2.5 on 2023-04-26 20:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230427_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='shop_brand',
        ),
        migrations.RemoveField(
            model_name='service',
            name='shop_service',
        ),
        migrations.AddField(
            model_name='service',
            name='user1',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 2, 18, 44, 815333), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='shopbrands',
            name='tv_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Service'),
        ),
        migrations.AlterField(
            model_name='shopservice',
            name='service_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Service'),
        ),
    ]
