# Generated by Django 2.2.5 on 2023-04-26 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230427_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 2, 19, 5, 738142), verbose_name='date published'),
        ),
    ]
