# Generated by Django 2.2.5 on 2023-04-27 20:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230427_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 2, 23, 6, 370104), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Location'),
        ),
    ]
